In [1]:
import pandas as pd

In [3]:
customer_df = pd.read_csv(
    "../_data/processed/customer_level_features.csv",
    parse_dates=["first_purchase", "last_purchase"]
)

customer_df.head()

,Customer_ID,total_transactions,total_quantity,total_revenue,avg_order_value,first_purchase,last_purchase,customer_lifetime_days,recency_days
0,12346.0,12,74285,77556.46,2281.072353,2009-12-14 08:34:00,2011-01-18 10:01:00,400,325
1,12347.0,8,3286,5633.32,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,1
2,12348.0,5,2714,2019.40,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,74
3,12349.0,4,1624,4428.69,25.306800,2010-04-29 13:20:00,2011-11-21 09:51:00,570,18
4,12350.0,1,197,334.40,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,309

In [4]:
CHURN_THRESHOLD_DAYS = 180

In [5]:
customer_df["churn"] = customer_df["recency_days"].apply(
    lambda x: 1 if x > CHURN_THRESHOLD_DAYS else 0
)

In [6]:
customer_df["churn"].value_counts(normalize=True)

churn
0    0.592038
1    0.407962
Name: proportion, dtype: float64

In [8]:
customer_df.to_csv(
    "../_data/processed/modeling_dataset.csv",
    index=False
)

customer_df.head()

,Customer_ID,total_transactions,total_quantity,total_revenue,avg_order_value,first_purchase,last_purchase,customer_lifetime_days,recency_days,churn
0,12346.0,12,74285,77556.46,2281.072353,2009-12-14 08:34:00,2011-01-18 10:01:00,400,325,1
1,12347.0,8,3286,5633.32,22.266087,2010-10-31 14:20:00,2011-12-07 15:52:00,402,1,0
2,12348.0,5,2714,2019.40,39.596078,2010-09-27 14:59:00,2011-09-25 13:13:00,362,74,0
3,12349.0,4,1624,4428.69,25.306800,2010-04-29 13:20:00,2011-11-21 09:51:00,570,18,0
4,12350.0,1,197,334.40,19.670588,2011-02-02 16:01:00,2011-02-02 16:01:00,0,309,1